var firstName = "Sasha";
var age = 19;
var isGirl = true;
var num = 14;
console.log(firstName);
console.log(age);
console.log(isGirl);
console.log(num);
var strArray = ["winter", "spring", "summer", "autumn"];
var numArray = [12, 2, 6, 21];
console.log(strArray);
console.log(numArray);
